# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.sidakCorrection <- function(p, n, cutoff = 1e-12) {
    .Call(`_sidakCorrection_sidakCorrection`, p, n, cutoff)
}

